### ISSUE TITLE
Make `group.id` Kafka connector field optional in WebConsole 

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1021]
Some time ago `group.id` was converted to a required field in the UI on my request.  Turns out that was not a good design (see #1013).  We should keep the field but make it optional.

@lalithsuresh 
@blp

**Comment by blp** [comment]
`group.id` will not be useful when fault tolerance is enabled, so when fault tolerance is widely used, `group.id` will not be useful. Moreover, I believe that we allow users to specify arbitrary key-value pair configuration for Kafka. Taken together, these might mean that we should remove a specific field for `group.id` from the UI, even an optional one, because users who really want it can specify it as a key-value pair.

**Comment by ryzhyk** [comment]
The WebConsole doesn't allow specifying arbitrary key-value pairs at the moment, but it probably should.  In any case, I have no objections against removing this field everywhere.

**Comment by blp** [comment]
Seems fine to make it optional as a first step, if that's an easier path to allowing arbitrary key-value pairs eventually.
