### ISSUE TITLE
sin is not supported 

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1094]
Currently the trigonometric function `sin` is not implemented.

**Comment by mihaibudiu** [comment]
There are several issues we have to figure out:
- does sin in Calcite work like in Postgres, or does it also support other data types
- how to write tests for floating point values. These are not exact results in general, so testing for equality may not work. We may need to adapt the testing framework in a significant way. Currently testing checks that the Zsets produced by the query and by parsing the expected output are identical, but this may not hold for floating point values, since the displayed value is an approximation of the real value.
