### ISSUE TITLE
Support for object storage connectors

### ISSUE THREAD

**Issue by MJFND** [feldera/feldera#1425]
Batch files are still used heavily across industry, having a connector to read and write to and from S3/GCS will unlock a lot of potential use cases.

I have used batch mostly, and will make it easy for folks to try it out if it starts to support. Setting up kafka and others locally would require some effort comparatively.

File formats: Parquet, Avro.

**Comment by mihaibudiu** [comment]
Certainly. What kind of file formats do you have in mind?

**Comment by mihaibudiu** [comment]
We have a CSV connector already.

**Comment by MJFND** [comment]
I updated with it.

**Comment by ryzhyk** [comment]
@MJFND , we also support JSON, and are working on adding Avro. Parquet is next on the roadmap.

**Comment by mihaibudiu** [comment]
We have started working on these. For Avro there is a preliminary PR which converts Avro schemas for SQL schemas: https://github.com/feldera/feldera/pull/1420.

**Comment by mihaibudiu** [comment]
Input adapters are easier, for output adapters you have to agree on a convention to represent deletions.

**Comment by MJFND** [comment]
Thanks, also open table formats support like Iceberg and Delta might be
helpful, they can provide ACID properties on data lake.

Most of them work well with Parquet.

**Comment by lalithsuresh** [comment]
@MJFND we've since added an input connector for S3 (which should also work for GCS). We have input and output connectors for DeltaTable as well including some examples. You can see an example here: https://www.feldera.com/docs/use_cases/fraud_detection/

We also support Parquet files and have Avro support in the queue. I'll close this for now. Let us know if you need any other connectors!
