### ISSUE TITLE
Support UNION types

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1809]
Supporting UNION types (similar to rust enums), this will ease modeling of various packets. For example, we consume BGP messages, a BGP message can be one of Open, Update, KeepAlive, Notification or RouteReferesh. See how we modeled it in our framework https://github.com/NetGauze/NetGauze/blob/main/crates/bgp-pkt/src/lib.rs#L60

(From @ahassany via Slack).

**Comment by mihaibudiu** [comment]
This one is a difficult topic, because we rely on Calcite for SQL parsing and validation, and Calcite does not have union types.
There has long been a desire to have a VARIANT data type in Calcite, which is a "universal" union type, i.e., a values of VARIANT type can have any other SQL type. But it's not a user-defined union type. I have long desired to contribute the VARIANT type to Calcite. If that's an adequate solution, I can see how this could be done.

**Comment by mihaibudiu** [comment]
The way we have chosen to implement JSON willl also support a form of union types: https://github.com/feldera/feldera/pull/2421
The VARIANT type that we are implementing is a dynamically-typed value (think Pyton).
So this will support union types naturally in SQL, but it won't be as convenient as a Rust enum.
The VARIANT will also be the way JSON is implemented.
Hopefully we'll land this soon.

**Comment by mihaibudiu** [comment]
I will close this issue, since I think VARIANT is the solution.
