### ISSUE TITLE
[SQL] allow `CREATE TABLE` and `CREATE VIEW` statements to specify connector information

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1891]
The Flink design is a possible starting point:
https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/dev/table/sql/create/#create-table

**Comment by gz** [comment]
I think this makes sense. some things to think about:

- we need: sinks (table), sources (views), local views
- other systems use `create sink/create source` for external facing things .. probably in part because it allows to re-use a view/table for two sinks/sources easily? as `create sink1 select * from view; create sink2 select * from view;` 
- another consideration is do we want more structure than `key = value` or is that enough (we currentlyhave a transport and config which are structured configuration. But they could also be expressed with key `transport.foo` or `connector.bla` etc. I'd be happy with that.. or flattened entirely.
- What's the configuration we generate from it (ideally it should just generate what we have currently but if it doesn't match nicely with the `key=value` property maybe we want to adjust it a bit and change the configuration of connectors instead)
