### ISSUE TITLE
Time-To-Live (TTL) Support

### ISSUE THREAD

**Issue by ngdto22x3** [feldera/feldera#1911]
Please implement ttl to reduce memory usage.

**Comment by ryzhyk** [comment]
Would you be able to describe your use case in more detail? This is a very loaded topic and the exact feature you need depends on how you plan to use it.

One related feature we already have (and are constantly improving) is [LATENESS](https://www.feldera.com/docs/sql/streaming#lateness-expressions), which annotates tables and views with an upper bound on out-of-ordedness of event arrival. This information is used by the static analyzer to prune data when it's no longer needed to compute new outputs. This mechanism is not perfect, since (1) there are situations where we could prune data based on lateness, but our static analyzer does not support them yet, and (2) in some situations additional information that is not captured by lateness is required for the static analyzer to prove that some state can be truncated, and we don't yet have a way to express that.

TTL could mean something completely different, e.g., insert a record that will be automatically deleted after a period of time. Unlike what I described above, this would produce user-visible changes, since all facts derived from the removed record would have to be retracted.

@ngdto22x3 , feel free to DM me in our [slack community](https://www.feldera.com/community) if you want to discuss your use case in more detail.

**Comment by mihaibudiu** [comment]
Is there a specification for TTL that you could recommend?

**Comment by ngdto22x3** [comment]
I am analyzing transactions in the determined cycles (current quarter, current month, current week). I have a good result when testing with LATENESS. However, KAFKA stream has a hight TPS, so memory is quickly used up. DBSP is saving unnecessary data history. TTL is used to release these records.

**Comment by mihaibudiu** [comment]
Is this in rust or sql?

**Comment by mihaibudiu** [comment]
Can you suggest a syntax for specifying TTL?

**Comment by ngdto22x3** [comment]
i think it will be similar to "lateness" syntax. 
CREATE TABLE order_pickup (
   when TIMESTAMP NOT NULL TTL INTERVAL '1:00' HOURS TO MINUTES,
   location VARCHAR
);

**Comment by ryzhyk** [comment]
@ngdto22x3 , this is precisely what lateness is supposed to solve. The reason you see memory grow is that we do not yet propagate the lateness annotation through all operators. In particular, we currently store complete inputs and outputs for debugging purposes.  We'll start with fixing that.

Is there any chance you could share your SQL queries? This would help us to identify other operators that do not release memory.

How are you using Feldera?  Are you building it from sources or are you using our docker images?

**Comment by mihaibudiu** [comment]
I don't think we have enough information to diagnose this problem
