### ISSUE TITLE
UI hangs on SQL program using MAP

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1935]
I tried a small SQL program with a MAP:

```sql
CREATE TABLE T(map Map<INT, INT>);
CREATE TABLE Keys(key INT);
CREATE VIEW V AS SELECT T.map[Keys.key] FROM T JOIN Keys ON TRUE;
```

The pipeline manager reported this error:
`pipeline-manager-1  | 2024-06-24 20:15:55 ERROR [manager] compiler task failed; error: 'Error parsing program schema: Unknown SQL type: MAP at line 14 column 22'`

However, the UI is stuck in the "COMPILING" state and does not show any error.

**Comment by mihaibudiu** [comment]
![image](https://github.com/feldera/feldera/assets/19397042/8b241f72-1a72-4977-8030-e2b0513c9742)

**Comment by gz** [comment]
if you add new types to
the compiler they will always need support in the backend and UI so you need to make an issue and make sure its supported everywhere

**Comment by mihaibudiu** [comment]
The ui should not hang no matter what program you type

**Comment by gz** [comment]
we rely on being able to have knowledge of all the types we encounter for things to work. So when you add a type you need to let other know.

**Comment by lalithsuresh** [comment]
@gz this seems like an unnecessarily coupled design. Can we relax it so we can iterate faster? The UI and pipeline-manager really shouldn't break any time Mihai adds a new type.

**Comment by gz** [comment]
This coupling was intentional. It's not just about the UI and the pipeline manager. Adapters/data formats also need to understand what types we have to support get data into a pipeline or how to write out a certain type for a data-format. If the enum for sqltypes is non-exhaustive everywhere then we don't know what broke in the code and we manually discover it by the time it happens (one-by-one). If the enum of all types is exhaustive, once we add a type we get a compile time everywhere where we need to know about all types and can go fix it.

https://github.com/feldera/feldera/blob/main/crates/pipeline-types/src/program_schema.rs#L201

**Comment by lalithsuresh** [comment]
I'm guessing this bubbled all the way to the UI to support the data viewer, which we intend to drop. Another clue this is overkill is that none of our demos or examples ever interact with the schema and types APIs. So I'm not sure the coupling is worth it.

I get the reasoning about exhaustiveness but the surface area here is far wider than it needs to be. Ideally, the coordination regarding types stayed local to the compiler and adapters, and does not need to leak till the UI.

**Comment by gz** [comment]
Adapters, UI, manager they all use the same JSON from the compiler to know about things. So once adapter need to know about it, the rest doesn't really matter.

FWIW I don't think this is really a big deal since adding a type is a very small effort. But we need @mihaibudiu to make an issue to support a certain type whenever he adds one instead of not telling us about it :)

**Comment by snkas** [comment]
The `compiler task failed;` means that the compiler task did not catch the error that was thrown, and as such its status does not get updated. I'll look into it :+1:

**Comment by snkas** [comment]
Please continue fix discussion in: PR https://github.com/feldera/feldera/pull/1941
