### ISSUE TITLE
Run benchmarks in public cloud when cloud deployment is updated

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2070]
We should run the benchmarks on our public cloud deployment regularly and add a report to the benchmarks repo. We could run the benchmarks whenever the cloud deployment is updated, or we could run them periodically (daily, weekly, etc.).

**Comment by aehmttw** [comment]
I discussed with @snkas today - the current concern with running cloud jobs regularly is that the disk is currently quite slow and using a more powerful disk also requires using a more powerful and expensive instance. Simon said that one of the todos for cloud is to use a different instance with an attached disk instead of a network disk. So for now, it probably makes most sense to run them manually.
