### ISSUE TITLE
[SQL] nexmark q15 can use linear aggregations 

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2250]

**Comment by ryzhyk** [comment]
The way to solve this and other cases where we cannot use linear aggregates directly (e.g., because of the semantics of NULLs) is to compute two or more  linear aggregates at the same time.  In this query, we want to compute a filtered count of elements in the group.  Instead, we can compute a two-tuple `(filtered count, count)`.  The second element in the tuple is >0 if the group is non-empty, which guarantees that the aggregate is not zero (a Cartesian product of groups is a group with pairwise operations; it's zero is a pair of zeros from each group).

I think we already have all the building blocks for this, but may need to add a convenience API.

**Comment by mihaibudiu** [comment]
This is actually the plan for #1341

**Comment by ryzhyk** [comment]
Maybe that's what you mean, but just to clarify, I am not suggesting computing multiple linear aggregates and joining them. Instead, we can compute all linear aggregates using a single operator, and also add an _artificial_ linear aggregate to the mix that simply counts the number of elements in the group, and thus guarantees that the weight is non-zero.

**Comment by mihaibudiu** [comment]
we can do the postprocessing in a separate map stage, but maybe you want that before the upsert

**Comment by ryzhyk** [comment]
> we can do the postprocessing in a separate map stage, but maybe you want that before the upsert

yes and yes

**Comment by ryzhyk** [comment]
@mihaibudiu , I think we can close this?
