### ISSUE TITLE
Load web console scripts earlier

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2471]
Currently the web console loads the scripts upon their use, however when bandwidth is not as high, this can take some time. For instance, the `useOpenPipeline.js` is about 7MB, which takes about 2s over a 28 Mbit/s connection plus RTTs.

Ideally, the scripts are loaded earlier on, such that the first click to open a pipeline is sped up.

**Comment by ryzhyk** [comment]
I've run into this multiple times too. The UI shouldn't allow users to click around until it's actually functional.

**Comment by ryzhyk** [comment]
@Karakatiza666  , I added "high priority" and "bug" labels to this issue. This has tripped us multiple times, I feel like we need to deal with it soon.  The high-level issue is that WebConsole doesn't behave well over slow connection. We know that at least part of the issue is loading the large library.
