### ISSUE TITLE
[sql] Waterline for LAG

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2847]
This might be on the more exotic side and probably not urgent.  I believe this view has a waterline, equal to the waterline of `t1`:

```sql
CREATE TABLE t1(
    x INT,
    ts TIMESTAMP NOT NULL LATENESS INTERVAL 1 HOUR
);

CREATE TABLE t2(
    y INT,
    ts TIMESTAMP NOT NULL LATENESS INTERVAL 1 HOUR
);

CREATE VIEW v
WITH ('emit_final' = 'ts')
AS
SELECT
    ts,
    x,
    LAG(x) OVER (ORDER BY ts)
FROM
    t1;
```

Today, the compiler complains:

```
Could not infer a waterline for column 'ts' of view 'v' which has an 'emit_final' annotation
   11|CREATE VIEW v
   12|WITH ('emit_final' = 'ts')
      ...
   19|    t1;
```

**Comment by mihaibudiu** [comment]
this will require adapting the dataflow analysis I have to handle correctly the lag operator function.
this is a funny one: the LAG function takes the input and the delayed input.
whatever is propagated from the input to the output may be monotone.
my existing dataflow analysis won't understand the fact that this function has an internally-generated input; it expects all inputs to come from the previous operator directly, that's why it will need a custom implementation.
it's doable, let me know if it becomes more urgent.
