### ISSUE TITLE
Data browser UI improvements.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#488]
- I think the quantiles slider should be a vertical slider, just like if we were browsing a really large table that doesn't fit in one page.
- The `<` , `>` arrows should just be PgUp/PgDn handlers. If we choose to keep the arrows (I still think we need to be able to use `PgUp`/`PgDn` to navigate the table, but it might be useful to have the arrows as well), they should be above the table and their position should immutable.  Right now they jump all over the place every time you press them and often slide outside the viewable area of the page.

**Comment by gz** [comment]
> Right now they jump all over the place every time you press them and often slide outside the viewable area of the page.

can you record a screencast of this and post here, I haven't observed this

**Comment by ryzhyk** [comment]
> can you record a screencast of this and post here, I haven't observed this

Clarification: this only happens when the table doesn't fit on the screen, so I need to scroll the page down to see the arrow buttons, but when I press one of them (or move the slider), it bounces back to the top of the page, so I need to scroll down once more to click again. Can you reproduce this?  If not, I'll record a screen capture.

**Comment by gz** [comment]
> I think the quantiles slider should be a vertical slider, just like if we were browsing a really large table that doesn't fit in one page.

Note that I thought about this at the time of implementing it but I think this (currently) doesn't work great/is confusing. 
Why: because right now the slider acts more like a jump to navigation element. Whenever you move it to a percentile and press next/back once it resets to the starting position. I found it was confusing when I had it stay at the place where you last moved it. (Note that we don't currently know can't find out the exact or approximate row count for a table/view). So, say you have a relation with low entry count (e.g., 100 or 1000 rows) and you move the slider to 70%, you might reach the end after 1 or 10 times pressing next, but you can't move the slider because we don't know where we are now after pressing back/next. So it is stuck at 70% implying that you are still there in the table which is the confusing part.

**Comment by ryzhyk** [comment]
Ah, I see.  My thinking was that because you know the quantiles, you can always determine the nearest quantiles to the current element, but actually the UI doesn't understand the ordering of elements and so cannot do this reliably. This will require some support from the backend.
