### ISSUE TITLE
Changing the SQL program can make pipeline config invalid, and there is no good way to recover from this.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#492]
- Start with a configured pipeline with at least one output connector. 
- Delete or rename the table that the connector is attached to.
- The config is now invalid, and the pipeline builder page will tell you so, however it doesn't provide a good way to recover, e.g., delete invalid connectors. The workaround I found was to add another connector, which somehow forces a good pipeline config to be saved.

**Comment by gz** [comment]
I think there are two options on how to approach this:

1. We display connectors that have become unattached in the builder as boxes without a connection (I think we currently don't) and we let the user either reattach it to a new table/view or delete it before they can run the pipeline (and when we display an error for this in pipeline management view we should probably give a hint on what a user needs to do)
2. We let pipelines run without attached connectors (the error is no longer an error and the user doesn't have to do anything to recover)

Probably (1) is the better way to go here since having an orphan connector in most cases will be unavoidable that the user should probably do something to reconnect it.

**Comment by ryzhyk** [comment]
Approach 1 sounds perfect to me.  Yes, we don't show orphan connectors now.

**Comment by Karakatiza666** [comment]
Fixed with https://github.com/feldera/feldera/pull/501
