### ISSUE TITLE
Improve the reporting of Rust errors

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#532]
We still occasionally generate invalid Rust code. The UI should report it as an internal error and help the user to submit a bug report to Feldera, including the SQL code.

**Comment by gz** [comment]
- [ ] We should make sure the link pre-populates the github issue (with appropriate labels, text, title, etc.): e.g., https://github.com/feldera/feldera/issues/new?labels=bug&title=title&body=text
- [ ] For errors that can't be fixed by the user, we should keep the display of the errors messages, stack trace etc to a minimum, and focus report it easily with a click
- [ ] For the compiler we have Rust Error and System Error: I think instead of name both of them "Unexpected System Error" in the front-end, e.g., the fact that we use rust is an implementation detail

- [ ]  Bonus: Don't think this is needed for first stab at this: Would be great to have automated reporting that a user-can opt in through a setting (e.g., the first time it happens we ask if this/and future errors should be automatically reported which then will open issues in the background)
