### ISSUE TITLE
Auto-layout doesn't work for output connectors

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#853]
Steps to reproduce:
- Create a new pipeline using any program with >1 outputs
- Add any two output Kafka connectors
- Connect output views with connectors so that the arrows cross over

![image](https://github.com/feldera/feldera/assets/8323135/af640ee3-3b58-449e-8c42-830e11eb9b41)

**Comment by gz** [comment]
Since we allow connections from multiple tables to the same connection it's impossible to avoid all overlaps here (so we currently don't even try, even though in some cases (including this one) the overlap could be prevented by re-ordering)... So not sure what exactly the fix should be here .. we can either be fine with overlaps and close as not fixed or have an auto-layout that fixes these trivial cases for output connectors by doing a best-effort layout

**Comment by ryzhyk** [comment]
Best effort is probably the right thing to do here, but I don't think it's a high priority.

**Comment by lalithsuresh** [comment]
Does not apply to the new web console.
